#!/bin/sh
NETWORK_NAME="Cellular"
TAG="LTE"

log() {
	echo ${1}
	logger -t ${TAG} ${1}
}

nmcli connection show --active | grep ${NETWORK_NAME}
if [ "${?}" == "0" ]; then
	log "shut down ${NETWORK_NAME}"
	nmcli c down ${NETWORK_NAME}
	exit 0
else
	log "${NETWORK_NAME} is not active"
	exit 1
fi
