#!/bin/sh

echo "[FotaClient]: Start" > /dev/kmsg

FILE=/data/recovery/Image
if [ ! -f "$FILE" ]; then
	mkdir -p /data/recovery
fi
cp -a /recovery/. /data/recovery/

UPG_FILE=/data/fota/upg_OTA_status
PKG_FILE=/data/update.swu
if [ -f "$UPG_FILE" ]&&[ -f "$PKG_FILE" ]; then
	rm -rf $PKG_FILE
fi

if [ -d "/data/fota" ]; then
    echo "[FotaClient]: /data/fota is existed"
else
    echo "[FotaClient]: creating /data/fota folder"
    mkdir -p "/data/fota/"
fi

alived=$(ps -aux| grep -v 'grep' | grep 'ota_daemon.py')
if [ "${alived}" != "" ]; then
    echo "[FotaClient]: Client is running"
else
    echo "[FotaClient]: Client is not running, restart"
    /usr/bin/python3 /usr/share/FotaClient/ota_daemon.pyc
fi