#!/bin/bash
TAG="mm_keepalive[$$]"
CONFIG_PATH=/etc/lte
LOCK_FILE=${CONFIG_PATH}/mm_keepalive.lock

log() {
    echo "${1}"
    logger -t ${TAG} ${1}
}

check_connection() {
    device=$(mmcli -L -K | grep 'modem-list.value' | awk -F ": " '{ print $2 }')
    state=$(mmcli -m ${device} -K | grep 'modem.generic.state ' | awk -F ": " '{ print $2 }')
    if [ "$state" != "connected" ]; then
        return 0
    else
        return 1
    fi
}

case "$1" in
start)
    log "Start keepalive service"
    echo $$ > ${LOCK_FILE}
    dbus-monitor --system "interface='org.freedesktop.ModemManager1.Modem',member='StateChanged'" |
    while read -r line && [ -e ${LOCK_FILE} ]; do
        log "${line}"
        if check_connection; then
            log "Check state is $state, reconnecting"
            /sbin/lte_connect
            exit 0
        fi
    done
    ;;
stop)
    log "Stop keepalive service"
    rm ${LOCK_FILE}
    ;;
restart)
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0